
package cn.zowee1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ILanguageService", targetNamespace = "http://service.yanshu.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ILanguageService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "say", targetNamespace = "http://service.yanshu.cn/", className = "cn.zowee1.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://service.yanshu.cn/", className = "cn.zowee1.SayResponse")
    public String say(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get", targetNamespace = "http://service.yanshu.cn/", className = "cn.zowee1.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://service.yanshu.cn/", className = "cn.zowee1.GetResponse")
    public String get(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
